_core:
  default_config_hash: LktZz2JrtX478yyO4ZCwnYOxr_0hKD-KNuH8aFLZRtQ
features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
  path: themes/custom/smash_lite/logo.svg
favicon:
  use_default: 1
slideshow_display: 1
slide1_head: 'Smash Lite is Multipurpose Drupal theme'
slide1_desc: "Smash Lite Theme is packed full of all the amazing features and options for you to create\r\n\r\n"
slide1_url: '#'
slide1_link_text: 'Learn More'
slide2_head: 'We Create Awesome Drupal Themes!'
slide2_desc: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
slide2_url: '#'
slide2_link_text: 'Learn More'
slide3_head: 'Welcome To Drupar'
slide3_desc: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'
slide3_url: '#'
slide3_link_text: 'Learn More'
show_header_image_details: 1
header_image: {  }
show_footer_first_details: 1
footer_image: {  }
footer_text: 'At Smash Lite the focus is always to serve our clients in the best way. We are an expert team of web developers, and designers that wants to build amazing websites and mobile apps'
show_contact_details: 1
footer_contact: 'Contact details'
location: '302 Smashing Infolabs IT PARK'
phone: '9997770001'
emails: Smash_lite@gmail.com
show_social_icon: 1
facebook_url: 'https://www.facebook.com/'
twitter_url: 'https://twitter.com/login'
instagram_url: 'https://www.instagram.com/'
linkedin_url: 'https://in.linkedin.com/'
youtube_url: 'https://www.youtube.com/'
vimeo_url: 'https://vimeo.com/'
telegram_url: 'https://telegram.com'
whatsapp_url: 'https://www.whatsapp.com/'
github_url: 'https://github.com/login'
footer_details: 1
footer_copyright: 'Â© 2022 All rights reserved.'
body_details: 1
arrow_up: right
